version: '3.1'
services:
  mysql:
    restart: always
    image: mariadb:10.4
    ports:
      - 3306:3306
    command: ['mysqld','--character-set-server=utf8']
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8083:80
    environment:
      PMA_HOSTS: mysql
    deploy:
      replicas: 1
  openemr:
    restart: always
    image: openemr/openemr:5.0.2
    ports:
      - 80:80
      - 443:443
    volumes:
      - logvolume01:/var/log
      - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    depends_on:
      - mysql
  mirth:
    image: nextgenhealthcare/connect:4.5.2
    container_name: mirth
    ports:
      - "8443:8443"  # HTTPS
      - "6661:6661"  # Puerto MLLP
    environment:
      - DATABASE=derby
    volumes:
      - mirth_data:/opt/mirth-connect/appdata

volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}
  mirth_data: {}
